export {VideoPlayerView} from './VideoPlayerView'
export {VideoPlayerView as VideoPlayerViewWeb} from './VideoPlayerView.web'
export {updateActiveVideoViewAsync} from './VideoPlayerModule'
export * from './VideoPlayerModule'
export type {VideoPlayerViewProps} from './VideoPlayer.types'
